version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: students-api
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=students
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - PORT = ${PORT}
    env_file:
      - .env.docker
    command: php artisan serve --host=0.0.0.0 --port=${PORT}  
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: